version: '3.7'

services:
    redis:
        image: redis:alpine

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=robot
            - POSTGRES_PASSWORD=django
            - POSTGRES_DB=robotixdb3

    app:
        image: robotixweb/backend:latest
        ports: 
            - "8000:8000"
        command: bash -c "python3 manage.py migrate --no-input"
        command: gunicorn RobotixWeb.wsgi --bind 0.0.0.0:8000 --workers 2 --threads 4 
        environment: 
            - DEBUG=1
        depends_on:
            - db

    celery:
        restart: on-failure
        image: robotixweb/backend:latest
        command: celery -A RobotixWeb worker -l info
        volumes:
        - ../RobotixWeb21:/RobotixWeb21
        environment:
            - DB_HOST=db
            - DB_NAME=robotixdb3
            - DB_USER=robot
            - DB_PASS=robotixdb3
        depends_on:
            - db
            - redis
            - app

    # nginx:
    #     image: nginx:latest
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    #         # - build_folder:/var/www/frontend
    #     depends_on:
    #         - app
volumes:
    postgres_data:
